version: "2"

services:
  prometheus:
    image: "prom/prometheus:v1.7.1"
    expose:
      - 9090
    links:
      - exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/data
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.local.path=/data/prometheus", "--storage.local.retention=1h"]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    links:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ../dist:/var/lib/grafana/plugins/grafana-flamegraph-panel
      - ./grafana.db:/var/lib/grafana/grafana.db
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=secret
    restart: unless-stopped

  exporter:
    image: samber/node-promfiler-demo
    ports:
      - 8080:8080
    expose:
      - 9142
    environment:
      - PORT=8080
    restart: unless-stopped

volumes:
    prometheus: {}
